from django.db import models

class Dashboard(models.Model):
    CPU = models.IntegerField()
    RAM = models.IntegerField()
    RAMU = models.BigIntegerField()
    RAMF = models.BigIntegerField()
    SWAP = models.IntegerField()
    SWAPF = models.BigIntegerField()
    SWAPU = models.BigIntegerField()
    #tempoFuncinamento = models.DateTimeField()
    disco = models.IntegerField()
    discoUsado = models.BigIntegerField()
    discoLivre = models.BigIntegerField()
    capacidadeDisco = models.BigIntegerField()
    year= models.IntegerField()
    month = models.IntegerField()
    day = models.IntegerField()
    hour = models.IntegerField()
    minute = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)
    tempof = models.CharField(max_length=30)
