# Generated by Django 2.1.2 on 2018-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU', models.FloatField()),
                ('RAM', models.FloatField()),
                ('SWAP', models.FloatField()),
                ('tempoFuncinamento', models.DateTimeField()),
                ('discoUsado', models.FloatField()),
                ('discoLivre', models.FloatField()),
                ('capacidadeDisco', models.IntegerField()),
                ('servicoTel', models.BooleanField()),
                ('servicoMsgInst', models.BooleanField()),
                ('servicoFax', models.BooleanField()),
                ('servicoEmail', models.BooleanField()),
                ('servicoBD', models.BooleanField()),
                ('servicoElastix', models.BooleanField()),
            ],
        ),
    ]
