# Generated by Django 2.1.1 on 2018-12-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU', models.FloatField()),
                ('RAM', models.FloatField()),
                ('SWAP', models.FloatField()),
                ('discoUsado', models.FloatField()),
                ('discoLivre', models.FloatField()),
                ('capacidadeDisco', models.BigIntegerField()),
            ],
        ),
    ]
