# Generated by Django 2.1.2 on 2018-11-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MusicaCategoria',
            fields=[
                ('musica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='musicas.Musica')),
                ('execRandom', models.BooleanField()),
                ('volume', models.CharField(max_length=5)),
            ],
            bases=('musicas.musica',),
        ),
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('musica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='musicas.Musica')),
                ('aplicacao', models.CharField(max_length=255)),
                ('formato', models.CharField(blank=True, max_length=30, null=True)),
            ],
            bases=('musicas.musica',),
        ),
    ]
