# Generated by Django 2.1.2 on 2018-11-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicas', '0001_initial'),
        ('numeros', '0001_initial'),
        ('anuncios', '0001_initial'),
        ('uras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentesDinamicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Anúncio'), ('2', 'Gravação'), ('3', 'Número de entrada'), ('4', 'URA'), ('5', 'Fila'), ('6', 'Chamada em grupo'), ('7', 'Condições de tempo'), ('8', 'Tronco')], max_length=1)),
                ('nome', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=40)),
                ('dicasDisp', models.BooleanField()),
                ('confirmCham', models.BooleanField()),
                ('prefixCID', models.IntegerField()),
                ('prefixTempoEspera', models.BooleanField()),
                ('infoAlerta', models.CharField(max_length=70)),
                ('restringAgentDin', models.BooleanField()),
                ('restricAgente', models.CharField(choices=[('1', 'Chamada como discada'), ('2', 'Sem Me-Siga ou Chamada para Frente'), ('3', 'Apenas extensões')], max_length=1)),
                ('estratChamada', models.CharField(choices=[('1', 'ringall'), ('2', 'leastrecent'), ('3', 'fewestcalls'), ('4', 'random'), ('5', 'rrmemory'), ('6', 'rrordered'), ('7', 'linear'), ('8', 'wrandom')], max_length=1)),
                ('preenchAuto', models.BooleanField()),
                ('igAgentesOcup', models.CharField(choices=[('1', 'Não'), ('2', 'Sim'), ('3', 'Sim + (chamadaemuso=não)'), ('4', 'Somente chamada em fila (chamadaemuso=não)')], max_length=1)),
                ('pesoFila', models.IntegerField()),
                ('tipoMus', models.CharField(choices=[('1', 'Apenas MoH'), ('2', 'Agente tocando'), ('3', 'Apenas chamar')], max_length=1)),
                ('quandoAnun', models.CharField(choices=[('1', 'Sempre'), ('2', 'Quando não há agentes livres'), ('3', 'Quando não há agentes prontos')], max_length=1)),
                ('gravacaoChamada', models.CharField(choices=[('1', 'Não'), ('2', 'wav49'), ('3', 'wav'), ('4', 'gsm')], max_length=1)),
                ('modoGravacao', models.CharField(choices=[('1', 'Incluir tempo de espera'), ('2', 'Após resposta')], max_length=1)),
                ('ajustVolumeChamada', models.CharField(choices=[('1', 'Sem ajuste'), ('2', '-4'), ('3', '-3'), ('4', '-2'), ('5', '-1'), ('6', '+1'), ('7', '+2'), ('8', '+3'), ('9', '+4')], max_length=1)),
                ('ajustVolumeAgente', models.CharField(choices=[('1', 'Sem ajuste'), ('2', '-4'), ('3', '-3'), ('4', '-2'), ('5', '-1'), ('6', '+1'), ('7', '+2'), ('8', '+3'), ('9', '+4')], max_length=1)),
                ('marcaChamOutroLug', models.BooleanField()),
                ('maxTempoEspera', models.TimeField(null=True)),
                ('modoMaxTempoEspera', models.CharField(choices=[('1', 'Estrito'), ('2', 'Livre')], max_length=1)),
                ('tempoLimAgent', models.TimeField(null=True)),
                ('reinicioTempoLimAg', models.BooleanField()),
                ('retentativa', models.TimeField(blank=True, null=True)),
                ('tempoConclusao', models.TimeField(blank=True, null=True)),
                ('atrasoMembro', models.TimeField(blank=True, null=True)),
                ('relatorioTemEsp', models.BooleanField()),
                ('pausaAutom', models.CharField(choices=[('1', 'Não'), ('2', 'Sim ,apenas nessa fila'), ('3', 'Sim, em todas as filas')], max_length=1)),
                ('pausaAutoOcup', models.BooleanField()),
                ('pausaAutoIndispo', models.BooleanField()),
                ('atrasoPausaAut', models.IntegerField()),
                ('maxChamadores', models.IntegerField()),
                ('unirVazio', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Estrito'), ('4', 'Extremamente estrito'), ('5', 'Livre')], max_length=1)),
                ('deixarVazio', models.CharField(choices=[('1', 'Não'), ('2', 'Sim'), ('3', 'Estrito'), ('4', 'Extremamente estrito'), ('5', 'Livre')], max_length=1)),
                ('limMembrosPenal', models.IntegerField()),
                ('frequencia', models.TimeField(blank=True, null=True)),
                ('posAnuncio', models.BooleanField()),
                ('anuncTempoEsp', models.CharField(choices=[('1', 'Não'), ('2', 'Sim'), ('3', 'Uma vez')], max_length=1)),
                ('frequenRepet', models.TimeField(blank=True, null=True)),
                ('eventChamado', models.CharField(choices=[('1', 'Desabilitado'), ('2', 'Habilitado')], max_length=1)),
                ('eventStatusMem', models.CharField(choices=[('1', 'Desabilitado'), ('2', 'Habilitado')], max_length=1)),
                ('nivelServico', models.TimeField()),
                ('filtro', models.CharField(blank=True, max_length=20, null=True)),
                ('destinoFalha', models.IntegerField()),
                ('reporEstat', models.CharField(choices=[('1', 'Nunca'), ('2', 'De hora em hora'), ('3', 'Diariamente'), ('4', 'Semanalmente'), ('5', 'Mensalmente'), ('6', 'Anualmente'), ('7', 'Reiniciar'), ('8', 'Customizar')], max_length=1)),
                ('anuncConfirmCham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncConfirmChamFila', to='anuncios.Anuncio')),
                ('anuncUniao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncUniaoFila', to='anuncios.Anuncio')),
                ('anuncioAgente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncioAgenteFila', to='anuncios.Anuncio')),
                ('menuSaidaURA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uras.URA')),
                ('musEspera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicas.Musica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembrosDinamicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filas.Fila')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numeros.NumeroEntrada')),
            ],
        ),
        migrations.AddField(
            model_name='agentesdinamicos',
            name='fila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filas.Fila'),
        ),
        migrations.AddField(
            model_name='agentesdinamicos',
            name='numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numeros.NumeroEntrada'),
        ),
    ]
