# Generated by Django 2.1.2 on 2018-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='destinoFalhaTipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
