# Generated by Django 2.1.2 on 2018-10-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numeros', '0001_initial'),
        ('filas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentesDinamicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filas.Fila')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numeros.NumeroEntrada')),
            ],
        ),
        migrations.CreateModel(
            name='MembrosDinamicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filas.Fila')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numeros.NumeroEntrada')),
            ],
        ),
    ]
