# Generated by Django 2.1.1 on 2018-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0002_fila_destinofalhatipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='destinoFalha',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
