# Generated by Django 2.1.1 on 2018-11-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0003_auto_20181112_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='atrasoMembro',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='frequenRepet',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='frequencia',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='maxTempoEspera',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='nivelServico',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='retentativa',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='tempoConclusao',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='tempoLimAgent',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
