# Generated by Django 2.1.2 on 2018-10-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroEntrada',
            fields=[
                ('numero', models.IntegerField()),
                ('origem', models.IntegerField()),
                ('atendido', models.BooleanField()),
                ('gravaChamada', models.BooleanField()),
                ('destino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinos.Destino')),
            ],
            bases=('destinos.destino',),
        ),
    ]
