# Generated by Django 2.1.1 on 2018-11-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroentrada',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
