# Generated by Django 2.1.2 on 2018-10-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeros', '0002_auto_20181024_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroentrada',
            name='atendido',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='numeroentrada',
            name='gravaChamada',
            field=models.BooleanField(),
        ),
    ]
