# Generated by Django 2.1.2 on 2018-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeros', '0003_auto_20181024_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroentrada',
            name='atendido',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='numeroentrada',
            name='gravaChamada',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
