# Generated by Django 2.1.1 on 2018-12-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadaEmGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Anúncio'), ('2', 'Gravação'), ('3', 'Número de entrada'), ('4', 'URA'), ('5', 'Fila'), ('6', 'Chamada em grupo'), ('7', 'Condições de tempo'), ('8', 'Tronco')], max_length=1)),
                ('descricao', models.CharField(max_length=70)),
                ('estrategia', models.CharField(choices=[('1', 'ringall'), ('2', 'ringall-prim'), ('3', 'hunt'), ('4', 'hunt-prim'), ('5', 'memoryhunt'), ('6', 'memoryhunt-prim'), ('7', 'firstavaible'), ('8', 'firstnotonphone')], max_length=1)),
                ('tempoChamada', models.IntegerField()),
                ('prefixCID', models.CharField(max_length=10)),
                ('infoAlerta', models.CharField(max_length=70)),
                ('igConfigCF', models.BooleanField()),
                ('igAgentOcupado', models.BooleanField()),
                ('atendeChamada', models.BooleanField()),
                ('confirmaChamada', models.BooleanField(null=True)),
                ('modo', models.CharField(choices=[('1', 'Padrão'), ('2', 'Valor fixo de CID'), ('3', 'Valor fixo de CID de chamadas externas'), ('4', 'Usar número discado'), ('5', 'Forçar número discado')], max_length=1)),
                ('valorFixoCID', models.CharField(blank=True, max_length=30, null=True)),
                ('gravarChamadas', models.CharField(choices=[('1', 'Sempre'), ('2', 'Sob demanda'), ('3', 'Nunca')], max_length=1)),
                ('destino', models.IntegerField(blank=True, null=True)),
                ('destinoTipo', models.CharField(blank=True, max_length=1, null=True)),
                ('anuncioCG', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncioCG', to='anuncios.Anuncio')),
                ('anuncioRemoto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncioRemotoCG', to='anuncios.Anuncio')),
                ('anuncioTardio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncioTardioCG', to='anuncios.Anuncio')),
                ('musicaEspera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicas.Musica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListaExtensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('ordem', models.IntegerField()),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadasgrupo.ChamadaEmGrupo')),
            ],
        ),
    ]
