# Generated by Django 2.1.2 on 2018-10-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
        ('anuncios', '0003_auto_20181010_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadaEmGrupo',
            fields=[
                ('descricao', models.CharField(max_length=70)),
                ('estrategia', models.CharField(choices=[('1', 'ringall'), ('2', 'ringall-prim'), ('3', 'hunt'), ('4', 'hunt-prim'), ('5', 'memoryhunt'), ('6', 'memoryhunt-prim'), ('7', 'firstavaible'), ('8', 'firstnotonphone')], max_length=1)),
                ('tempoChamada', models.IntegerField()),
                ('prefixCID', models.CharField(max_length=10)),
                ('infoAlerta', models.CharField(max_length=70)),
                ('igConfigCF', models.BooleanField()),
                ('igAgentOcupado', models.BooleanField()),
                ('atendeChamada', models.BooleanField()),
                ('confirmaChamada', models.BooleanField()),
                ('modo', models.CharField(choices=[('1', 'Padrão'), ('2', 'Valor fixo de CID'), ('3', 'Valor fixo de CID de chamadas externas'), ('4', 'Usar número discado'), ('5', 'Forçar número discado')], max_length=1)),
                ('valorFixoCID', models.CharField(blank=True, max_length=30, null=True)),
                ('gravarChamadas', models.CharField(choices=[('1', 'Sempre'), ('2', 'Sob demanda'), ('3', 'Nunca')], max_length=1)),
                ('destino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='destinoCE', serialize=False, to='destinos.Destino')),
                ('anuncioCG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncioCG', to='anuncios.Anuncio')),
                ('anuncioRemoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncioRemotoCG', to='anuncios.Anuncio')),
                ('anuncioTardio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncioTardioCG', to='anuncios.Anuncio')),
            ],
            bases=('destinos.destino',),
        ),
    ]
