# Generated by Django 2.1.2 on 2018-10-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numeros', '0001_initial'),
        ('chamadasgrupo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaExtensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadasgrupo.ChamadaEmGrupo')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numeros.NumeroEntrada')),
            ],
        ),
    ]
