# Generated by Django 2.1.2 on 2018-11-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamadasgrupo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamadaemgrupo',
            name='anuncioRemoto',
        ),
        migrations.RemoveField(
            model_name='chamadaemgrupo',
            name='anuncioTardio',
        ),
    ]
