# Generated by Django 2.1.2 on 2018-11-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
        ('chamadasgrupo', '0002_auto_20181109_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadaemgrupo',
            name='anuncioRemoto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncioRemotoCG', to='anuncios.Anuncio'),
        ),
        migrations.AddField(
            model_name='chamadaemgrupo',
            name='anuncioTardio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncioTardioCG', to='anuncios.Anuncio'),
        ),
    ]
