# Generated by Django 2.1.2 on 2018-10-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
        ('chamadasgrupo', '0002_listaextensao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadaemgrupo',
            name='musicaEspera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicas.Musica'),
            preserve_default=False,
        ),
    ]
