# Generated by Django 2.1.2 on 2018-11-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamadasgrupo', '0003_chamadaemgrupo_musicaespera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadaemgrupo',
            name='anuncioCG',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncioCG', to='anuncios.Anuncio'),
        ),
        migrations.AlterField(
            model_name='chamadaemgrupo',
            name='anuncioRemoto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncioRemotoCG', to='anuncios.Anuncio'),
        ),
        migrations.AlterField(
            model_name='chamadaemgrupo',
            name='anuncioTardio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncioTardioCG', to='anuncios.Anuncio'),
        ),
        migrations.AlterField(
            model_name='chamadaemgrupo',
            name='confirmaChamada',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chamadaemgrupo',
            name='musicaEspera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicas.Musica'),
        ),
    ]
