# Generated by Django 2.1.2 on 2018-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadasgrupo', '0003_auto_20181109_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadaemgrupo',
            name='destinoTipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
