# Generated by Django 2.1.1 on 2018-11-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadasgrupo', '0004_chamadaemgrupo_destinotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadaemgrupo',
            name='destino',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
