# Generated by Django 2.1.1 on 2018-11-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadasgrupo', '0005_auto_20181112_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaextensao',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
