# Generated by Django 2.1.2 on 2018-10-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('repeticao', models.IntegerField(blank=True, max_length=10, null=True)),
                ('pula', models.BooleanField()),
                ('retornaURA', models.BooleanField()),
                ('canalNaoResp', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
