# Generated by Django 2.1.2 on 2018-10-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='id',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='destino',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinos.Destino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='repeticao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
