# Generated by Django 2.1.2 on 2018-10-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
        ('anuncios', '0002_auto_20181010_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gravacao',
            fields=[
                ('destino_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinos.Destino')),
                ('nome', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=70)),
            ],
            bases=('destinos.destino',),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='gravacaoAn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anuncios.Gravacao'),
            preserve_default=False,
        ),
    ]
