# Generated by Django 2.1.2 on 2018-10-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
        ('anuncios', '0003_auto_20181010_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravacao',
            name='musica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicas.MusicaCategoria'),
        ),
    ]
