# Generated by Django 2.1.2 on 2018-10-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_auto_20181015_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravacao',
            name='musica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicas.MusicaCategoria'),
        ),
    ]
