# Generated by Django 2.1.2 on 2018-11-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_auto_20181015_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='gravacaoAn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anuncios.Gravacao'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='repeticao',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gravacao',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gravacao',
            name='musica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicas.MusicaCategoria'),
        ),
    ]
