# Generated by Django 2.1.2 on 2018-11-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_auto_20181105_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravacao',
            name='musica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicas.MusicaCategoria'),
        ),
    ]
