# Generated by Django 2.1.2 on 2018-10-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoTempo',
            fields=[
                ('nome', models.CharField(max_length=30)),
                ('destinoCoincide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='destinoCoincideCT', to='destinos.Destino')),
                ('destinoNaoCoincide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='destinoNaoCoincideCT', serialize=False, to='destinos.Destino')),
            ],
            bases=('destinos.destino',),
        ),
    ]
