# Generated by Django 2.1.1 on 2018-11-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condicoestempo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicaotempo',
            name='destinoCoincideTipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='condicaotempo',
            name='destinoNaoCoincideTipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='condicaotempo',
            name='destinoCoincide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condicaotempo',
            name='destinoNaoCoincide',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
