# Generated by Django 2.1.1 on 2018-12-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegraManipulaNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precedente', models.IntegerField()),
                ('prefixo', models.IntegerField()),
                ('padrao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tronco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Anúncio'), ('2', 'Gravação'), ('3', 'Número de entrada'), ('4', 'URA'), ('5', 'Fila'), ('6', 'Chamada em grupo'), ('7', 'Condições de tempo'), ('8', 'Tronco')], max_length=1)),
                ('nome', models.CharField(max_length=40)),
                ('callerIDSaida', models.CharField(blank=True, max_length=30, null=True)),
                ('opcoesCID', models.CharField(choices=[('1', 'Permitir qualquer CID'), ('2', 'Bloquear CIDs estrangeiros'), ('3', 'Remover CNAM'), ('4', 'Forçar tronco CID')], max_length=1)),
                ('maxCanais', models.IntegerField(blank=True, null=True)),
                ('opcoesDiskAsterisk', models.CharField(blank=True, max_length=30, null=True)),
                ('contSeOcup', models.BooleanField()),
                ('desabTronco', models.BooleanField()),
                ('prefixChamSaida', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TroncoCustomizado',
            fields=[
                ('tronco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troncos.Tronco')),
                ('stringChamada', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('troncos.tronco',),
        ),
        migrations.CreateModel(
            name='TroncoIAX',
            fields=[
                ('tronco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troncos.Tronco')),
                ('nomeTronco', models.CharField(blank=True, max_length=40, null=True)),
                ('detalhesPEER', models.TextField(blank=True, null=True)),
                ('contextoUsuario', models.CharField(blank=True, max_length=40, null=True)),
                ('detalhesUsuario', models.TextField(blank=True, null=True)),
                ('stringRegistro', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('troncos.tronco',),
        ),
        migrations.CreateModel(
            name='TroncoSIP',
            fields=[
                ('tronco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='troncos.Tronco')),
                ('nomeTronco', models.CharField(blank=True, max_length=40, null=True)),
                ('detalhesPEER', models.TextField(blank=True, null=True)),
                ('contextoUsuario', models.CharField(blank=True, max_length=40, null=True)),
                ('detalhesUsuario', models.TextField(blank=True, null=True)),
                ('stringRegistro', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('troncos.tronco',),
        ),
        migrations.AddField(
            model_name='regramanipulanum',
            name='tronco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troncos.Tronco'),
        ),
    ]
