# Generated by Django 2.1.2 on 2018-10-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
        ('anuncios', '0003_auto_20181010_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoURA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='destinos.Destino')),
                ('retornar', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='URA',
            fields=[
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=10)),
                ('discarDireto', models.CharField(choices=[('1', 'Desabilitado'), ('2', 'Ramais')], max_length=1)),
                ('timeout', models.IntegerField()),
                ('tentativasInvalidas', models.IntegerField()),
                ('anexAnuncInvalid', models.BooleanField()),
                ('returnInvalid', models.BooleanField()),
                ('destinoInvalid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='destinoInvalidURA', to='destinos.Destino')),
                ('retentativasTimeout', models.IntegerField()),
                ('anexAnuncTimeout', models.BooleanField()),
                ('retornarTimeout', models.BooleanField()),
                ('destinoTimeout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='destinoTimeoutURA', serialize=False, to='destinos.Destino')),
                ('returnURACaixaPostal', models.BooleanField()),
                ('anuncioUra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Anuncio')),
                ('gravInvalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravInvalidURA', to='anuncios.Gravacao')),
                ('gravRepetInvalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Gravacao')),
                ('gravRetentTimeout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravRepetInvalidURA', to='anuncios.Gravacao')),
                ('gravTimeout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravTimeoutURA', to='anuncios.Gravacao')),
            ],
            bases=('destinos.destino',),
        ),
        migrations.AddField(
            model_name='opcaoura',
            name='ura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uras.URA'),
        ),
    ]
