# Generated by Django 2.1.2 on 2018-11-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ura',
            name='anuncioUra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.Anuncio'),
        ),
        migrations.AlterField(
            model_name='ura',
            name='gravInvalid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravInvalidURA', to='anuncios.Gravacao'),
        ),
        migrations.AlterField(
            model_name='ura',
            name='gravRepetInvalid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.Gravacao'),
        ),
        migrations.AlterField(
            model_name='ura',
            name='gravRetentTimeout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravRepetInvalidURA', to='anuncios.Gravacao'),
        ),
        migrations.AlterField(
            model_name='ura',
            name='gravTimeout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravTimeoutURA', to='anuncios.Gravacao'),
        ),
    ]
