# Generated by Django 2.1.1 on 2018-11-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ura',
            name='destinoInvalid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura',
            name='destinoTimeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura',
            name='discarDireto',
            field=models.CharField(choices=[('0', 'Desabilitado'), ('1', 'Ramais')], max_length=1),
        ),
    ]
