# Generated by Django 2.1.1 on 2018-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uras', '0002_auto_20181123_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ura',
            name='retentativasTimeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ura',
            name='tentativasInvalidas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
