# Generated by Django 2.1.1 on 2018-11-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uras', '0003_auto_20181123_1145'),
    ]

    operations = [        
        migrations.AlterField(
            model_name='ura',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
