# Generated by Django 2.1.1 on 2018-11-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uras', '0004_auto_20181123_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='ura',
            name='destinoInvalidTipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ura',
            name='destinoTimeoutTipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
